import = ["~/.config/alacritty/themes/themes/colornight.toml"]

[window]

dimensions = { columns = 100, lines = 40}
position = { x = 700, y = 300 }
padding = { x = 10}
opacity = 0.9
decorations = "none"

[font]
normal = { family = "JetBrainsMono", style = "Bold" }
size = 13.0

